### ISSUE TITLE
403 from private registry when trying to run 'opctl run init'

### ISSUE THREAD

**Issue by DZwell** [opspec-io/cli#19]
Had to manually run 'docker pull quay.io/.../...' even though I was logged in to quay via the command line.

**Comment by chrisdostert** [comment]
regression introduced here: https://github.com/opspec-io/engine-sdk-golang/commit/bf1edee0b8b77bd2c0323514371237d76b83e656#diff-6e5ec2ae73d19d88bdfaa204f3a83003L50

**Comment by chrisdostert** [comment]
the workaround until the fix is in is to run `docker pull PRIVATE_IMAGE_REF`

**Comment by chrisdostert** [comment]
bind mounting the hosts docker config is being deprecated so i'm updating this to a nofix.

the guidance moving forward is to taking any private registry credentials in as parameters to your ops that rely on that and doing a docker login as part of your op.

The benefits of this are that your ops inputs are fully defined vs relying on out of band configuration of docker on the op engine host
