### ISSUE TITLE
opctl does not wait for parallel op containers to die before returning

### ISSUE THREAD

**Issue by chrisdostert** [opspec-io/cli#8]
If an op has multiple sub ops configured to run in parallel and ctrl+c is pressed, opctl does not wait for all ops to end before returning. This differs from the behavior when multiple sub ops are run in parallel.

**Comment by poppuyo** [comment]
One side-effect of this is that ops might not have been killed when they are rerun. This can be a problem when ports are being bound, as the underlying apps might throw as their ports are taken by their (not-yet-killed) predecessor.
